package com.db.pojo;

public class allfood {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allfood.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allfood.name
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allfood.day
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allfood.img
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allfood.id
     *
     * @return the value of allfood.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allfood.id
     *
     * @param id the value for allfood.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allfood.name
     *
     * @return the value of allfood.name
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allfood.name
     *
     * @param name the value for allfood.name
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allfood.day
     *
     * @return the value of allfood.day
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allfood.day
     *
     * @param day the value for allfood.day
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allfood.img
     *
     * @return the value of allfood.img
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allfood.img
     *
     * @param img the value for allfood.img
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}