package com.db.pojo;

import java.util.Date;

public class compstock extends compstockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compstock.start
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private Date start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compstock.price
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compstock.number
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private Double number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compstock.start
     *
     * @return the value of compstock.start
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compstock.start
     *
     * @param start the value for compstock.start
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compstock.price
     *
     * @return the value of compstock.price
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compstock.price
     *
     * @param price the value for compstock.price
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compstock.number
     *
     * @return the value of compstock.number
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public Double getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compstock.number
     *
     * @param number the value for compstock.number
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setNumber(Double number) {
        this.number = number;
    }
}