package com.db.pojo;

public class manager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managername
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private String managername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.password
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.id
     *
     * @return the value of manager.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.id
     *
     * @param id the value for manager.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managername
     *
     * @return the value of manager.managername
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public String getManagername() {
        return managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managername
     *
     * @param managername the value for manager.managername
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setManagername(String managername) {
        this.managername = managername == null ? null : managername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.password
     *
     * @return the value of manager.password
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.password
     *
     * @param password the value for manager.password
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}