package com.db.pojo;

public class onlineuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onlineuser.username
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onlineuser.password
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onlineuser.ip
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onlineuser.phone
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private Integer phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onlineuser.username
     *
     * @return the value of onlineuser.username
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onlineuser.username
     *
     * @param username the value for onlineuser.username
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onlineuser.password
     *
     * @return the value of onlineuser.password
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onlineuser.password
     *
     * @param password the value for onlineuser.password
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onlineuser.ip
     *
     * @return the value of onlineuser.ip
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onlineuser.ip
     *
     * @param ip the value for onlineuser.ip
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onlineuser.phone
     *
     * @return the value of onlineuser.phone
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onlineuser.phone
     *
     * @param phone the value for onlineuser.phone
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }
}