package com.db.pojo;

public class owner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.username
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.password
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.id
     *
     * @return the value of owner.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.id
     *
     * @param id the value for owner.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.username
     *
     * @return the value of owner.username
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.username
     *
     * @param username the value for owner.username
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.password
     *
     * @return the value of owner.password
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.password
     *
     * @param password the value for owner.password
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}