package com.db.pojo;

public class storestockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storestock.id
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storestock.ownerid
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    private Integer ownerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storestock.quality
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    private String quality;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storestock.id
     *
     * @return the value of storestock.id
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storestock.id
     *
     * @param id the value for storestock.id
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storestock.ownerid
     *
     * @return the value of storestock.ownerid
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    public Integer getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storestock.ownerid
     *
     * @param ownerid the value for storestock.ownerid
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    public void setOwnerid(Integer ownerid) {
        this.ownerid = ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storestock.quality
     *
     * @return the value of storestock.quality
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    public String getQuality() {
        return quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storestock.quality
     *
     * @param quality the value for storestock.quality
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    public void setQuality(String quality) {
        this.quality = quality == null ? null : quality.trim();
    }
}