package com.db.pojo;

import java.util.Date;

public class storestock extends storestockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storestock.inprice
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    private Double inprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storestock.outprice
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    private Double outprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storestock.number
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    private Double number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storestock.start
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    private Date start;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storestock.inprice
     *
     * @return the value of storestock.inprice
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    public Double getInprice() {
        return inprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storestock.inprice
     *
     * @param inprice the value for storestock.inprice
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    public void setInprice(Double inprice) {
        this.inprice = inprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storestock.outprice
     *
     * @return the value of storestock.outprice
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    public Double getOutprice() {
        return outprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storestock.outprice
     *
     * @param outprice the value for storestock.outprice
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    public void setOutprice(Double outprice) {
        this.outprice = outprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storestock.number
     *
     * @return the value of storestock.number
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    public Double getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storestock.number
     *
     * @param number the value for storestock.number
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    public void setNumber(Double number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storestock.start
     *
     * @return the value of storestock.start
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storestock.start
     *
     * @param start the value for storestock.start
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    public void setStart(Date start) {
        this.start = start;
    }
}