package com.db.pojo;

public class storecash {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storecash.id
     *
     * @mbggenerated Fri Dec 16 20:17:01 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storecash.all
     *
     * @mbggenerated Fri Dec 16 20:17:01 CST 2022
     */
    private Double all;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storecash.id
     *
     * @return the value of storecash.id
     *
     * @mbggenerated Fri Dec 16 20:17:01 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storecash.id
     *
     * @param id the value for storecash.id
     *
     * @mbggenerated Fri Dec 16 20:17:01 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storecash.all
     *
     * @return the value of storecash.all
     *
     * @mbggenerated Fri Dec 16 20:17:01 CST 2022
     */
    public Double getAll() {
        return all;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storecash.all
     *
     * @param all the value for storecash.all
     *
     * @mbggenerated Fri Dec 16 20:17:01 CST 2022
     */
    public void setAll(Double all) {
        this.all = all;
    }
}