package com.db.pojo;

public class store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.ip
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.ownerid
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private Integer ownerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.id
     *
     * @return the value of store.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.id
     *
     * @param id the value for store.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.ip
     *
     * @return the value of store.ip
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.ip
     *
     * @param ip the value for store.ip
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.ownerid
     *
     * @return the value of store.ownerid
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public Integer getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.ownerid
     *
     * @param ownerid the value for store.ownerid
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setOwnerid(Integer ownerid) {
        this.ownerid = ownerid;
    }
}