package com.db.pojo;

public class subscribe extends subscribeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscribe.number
     *
     * @mbggenerated Sat Dec 10 21:27:11 CST 2022
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscribe.number
     *
     * @return the value of subscribe.number
     *
     * @mbggenerated Sat Dec 10 21:27:11 CST 2022
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscribe.number
     *
     * @param number the value for subscribe.number
     *
     * @mbggenerated Sat Dec 10 21:27:11 CST 2022
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}