package com.db.pojo;

public class vipuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.name
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.ip
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.phone
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    private Integer phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.id
     *
     * @return the value of vipuser.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.id
     *
     * @param id the value for vipuser.id
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.name
     *
     * @return the value of vipuser.name
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.name
     *
     * @param name the value for vipuser.name
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.ip
     *
     * @return the value of vipuser.ip
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.ip
     *
     * @param ip the value for vipuser.ip
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.phone
     *
     * @return the value of vipuser.phone
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.phone
     *
     * @param phone the value for vipuser.phone
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }
}