package com.db.mapper;

import com.db.pojo.allfood;
import com.db.pojo.allfoodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface allfoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allfood
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int countByExample(allfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allfood
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int deleteByExample(allfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allfood
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allfood
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int insert(allfood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allfood
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int insertSelective(allfood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allfood
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    List<allfood> selectByExample(allfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allfood
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    allfood selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allfood
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByExampleSelective(@Param("record") allfood record, @Param("example") allfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allfood
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByExample(@Param("record") allfood record, @Param("example") allfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allfood
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByPrimaryKeySelective(allfood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allfood
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByPrimaryKey(allfood record);
}