package com.db.mapper;

import com.db.pojo.compstock;
import com.db.pojo.compstockExample;
import com.db.pojo.compstockKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface compstockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compstock
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int countByExample(compstockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compstock
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int deleteByExample(compstockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compstock
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int deleteByPrimaryKey(compstockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compstock
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int insert(compstock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compstock
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int insertSelective(compstock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compstock
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    List<compstock> selectByExample(compstockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compstock
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    compstock selectByPrimaryKey(compstockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compstock
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByExampleSelective(@Param("record") compstock record, @Param("example") compstockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compstock
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByExample(@Param("record") compstock record, @Param("example") compstockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compstock
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByPrimaryKeySelective(compstock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compstock
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByPrimaryKey(compstock record);
}