package com.db.mapper;

import com.db.pojo.owner;
import com.db.pojo.ownerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ownerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int countByExample(ownerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int deleteByExample(ownerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int insert(owner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int insertSelective(owner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    List<owner> selectByExample(ownerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    owner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByExampleSelective(@Param("record") owner record, @Param("example") ownerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByExample(@Param("record") owner record, @Param("example") ownerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByPrimaryKeySelective(owner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByPrimaryKey(owner record);
}