package com.db.mapper;

import com.db.pojo.storestock;
import com.db.pojo.storestockExample;
import com.db.pojo.storestockKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface storestockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storestock
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    int countByExample(storestockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storestock
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    int deleteByExample(storestockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storestock
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    int deleteByPrimaryKey(storestockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storestock
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    int insert(storestock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storestock
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    int insertSelective(storestock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storestock
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    List<storestock> selectByExample(storestockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storestock
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    storestock selectByPrimaryKey(storestockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storestock
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    int updateByExampleSelective(@Param("record") storestock record, @Param("example") storestockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storestock
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    int updateByExample(@Param("record") storestock record, @Param("example") storestockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storestock
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    int updateByPrimaryKeySelective(storestock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storestock
     *
     * @mbggenerated Fri Dec 16 21:32:02 CST 2022
     */
    int updateByPrimaryKey(storestock record);
}