package com.db.mapper;

import com.db.pojo.subscribe;
import com.db.pojo.subscribeExample;
import com.db.pojo.subscribeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface subscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated Sat Dec 10 21:27:11 CST 2022
     */
    int countByExample(subscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated Sat Dec 10 21:27:11 CST 2022
     */
    int deleteByExample(subscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated Sat Dec 10 21:27:11 CST 2022
     */
    int deleteByPrimaryKey(subscribeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated Sat Dec 10 21:27:11 CST 2022
     */
    int insert(subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated Sat Dec 10 21:27:11 CST 2022
     */
    int insertSelective(subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated Sat Dec 10 21:27:11 CST 2022
     */
    List<subscribe> selectByExample(subscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated Sat Dec 10 21:27:11 CST 2022
     */
    subscribe selectByPrimaryKey(subscribeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated Sat Dec 10 21:27:11 CST 2022
     */
    int updateByExampleSelective(@Param("record") subscribe record, @Param("example") subscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated Sat Dec 10 21:27:11 CST 2022
     */
    int updateByExample(@Param("record") subscribe record, @Param("example") subscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated Sat Dec 10 21:27:11 CST 2022
     */
    int updateByPrimaryKeySelective(subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated Sat Dec 10 21:27:11 CST 2022
     */
    int updateByPrimaryKey(subscribe record);
}