package com.db.mapper;

import com.db.pojo.vipuser;
import com.db.pojo.vipuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface vipuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipuser
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int countByExample(vipuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipuser
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int deleteByExample(vipuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipuser
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipuser
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int insert(vipuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipuser
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int insertSelective(vipuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipuser
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    List<vipuser> selectByExample(vipuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipuser
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    vipuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipuser
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByExampleSelective(@Param("record") vipuser record, @Param("example") vipuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipuser
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByExample(@Param("record") vipuser record, @Param("example") vipuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipuser
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByPrimaryKeySelective(vipuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipuser
     *
     * @mbggenerated Fri Dec 09 10:36:56 CST 2022
     */
    int updateByPrimaryKey(vipuser record);
}